# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Approach' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Approach	
  pod 'GoogleSignIn', '5.0.2'
  pod 'BraintreeDropIn', '9.2.0'
  pod 'Braintree/PayPal', '5.4.2'
  pod 'Alamofire'

end
